name: Release All Base Docker images

on:
  workflow_dispatch:
    inputs:
      commit:
        description: "Commit sha to build from"
        required: true
      tag:
        type: string
        description: "New tag for the image"
        default: test
        required: true
      latest:
        type: boolean
        description: "Also update latest tag"
        required: true
        default: false

jobs:
  build-push-multi-arch-images:
    runs-on: ubuntu-latest-16-cores
    strategy:
      matrix:
        arch: ["linux/amd64,linux/arm64"]
        image: [base-server, base-builder, base-admin-tools]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.commit }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Metatags for the image
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: temporalio/${{ matrix.image }}
          tags: |
            type=raw,value=${{ github.event.inputs.tag }}
            type=sha,value=${{ github.event.inputs.commit }}
            type=raw,value=latest,enable=${{ github.event.inputs.latest }}

      - name: Build and Push the image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: docker/base-images/${{ matrix.image }}.Dockerfile
          platforms: ${{ matrix.arch }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-push-amd64-images:
    runs-on: ubuntu-latest-16-cores
    strategy:
      matrix:
        arch: [linux/amd64]
        image: [base-ci-builder]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.commit }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Metatags for the image
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: temporalio/${{ matrix.image }}
          tags: |
            type=raw,value=${{ github.event.inputs.tag }}
            type=sha,value=${{ github.event.inputs.commit }}
            type=raw,value=latest,enable=${{ github.event.inputs.latest }}

      - name: Build and Push the image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: docker/base-images/${{ matrix.image }}.Dockerfile
          platforms: ${{ matrix.arch }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
