name: Release Base-* Docker image

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Target base image"
        type: choice
        options:
          - base-server
          - base-builder
          - base-admin-tools
          - base-ci-builder
        required: true
      commit:
        description: "Commit sha to build from"
        required: true
      tag:
        description: "New tag for the image"
        required: true
      arch:
        description: "Platform architecture"
        type: choice
        options:
          - linux/amd64,linux/arm64
          - linux/amd64
          - linux/arm64
        required: true
        default: linux/amd64,linux/arm64

jobs:
  build-push-images:
    runs-on: ubuntu-latest-16-cores
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.commit }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Metatags for the image
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: temporalio/${{ github.event.inputs.target }}
          tags: ${{ github.event.inputs.tag }}

      - name: Build-Push Base-* image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: docker/base-images/${{ github.event.inputs.target }}.Dockerfile
          platforms: ${{ github.event.inputs.arch }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
