name: "Update Submodule"

on:
  workflow_dispatch:
    inputs:
      repo:
        description: "Submodule to update"
        required: true
      branch:
        description: "Branch of the submodule to update"
        required: true

jobs:
  sync:
    name: "Update submodules"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Create and switch branch
        env:
          BRANCH: ${{ github.event.inputs.branch }}
        run: |
          if [[ $BRANCH == master ]]; then BRANCH=main; fi
          git switch "$BRANCH" || git switch -c "$BRANCH"

      - name: Update Submodule branch
        env:
          SUBMODULE: ${{ github.event.inputs.repo }}
          BRANCH: ${{ github.event.inputs.branch }}
        run: |
          git config --file=.gitmodules submodule.$SUBMODULE.branch "$BRANCH"
          git submodule update --init --recursive --remote

      - name: Commit update
        env:
          SUBMODULE: ${{ github.event.inputs.repo }}
          BRANCH: ${{ github.event.inputs.branch }}
          TOKEN: ${{ secrets.COMMANDER_DATA_TOKEN }}
        run: |
          git config --local user.name 'Temporal Data (cicd)'
          git config --local user.email 'commander-data@temporal.io'
          git remote set-url origin https://x-access-token:$TOKEN@github.com/${{ github.repository }}
          git add .
          git commit -m "Update $SUBMODULE submodule for branch $BRANCH"
          git push --set-upstream origin "$BRANCH" || echo "No changes to commit"
